-- Create recipes table
CREATE TABLE recipes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  kcal INTEGER NOT NULL,
  protein REAL NOT NULL,
  carbs REAL NOT NULL,
  fat REAL NOT NULL,
  tags TEXT NOT NULL, -- JSON array as string
  warning_level TEXT DEFAULT 'none', -- 'none', 'caution', 'avoid'
  warning_reason TEXT,
  ingredients TEXT NOT NULL, -- JSONB array
  is_custom BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create meal_plans table
CREATE TABLE meal_plans (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  selected_ids TEXT NOT NULL, -- JSON array as string
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert lunch recipes (12)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('lunch_1', 'Salmón a la mantequilla con verduras', 'Salmón fresco cocinado en mantequilla con brócoli y zanahoria', 520, 48, 12, 28, '["omega-3","anti-inflam"]', 'none', NULL, '[{"name":"Salmón fresco","qty":250,"unit":"g","category":"Pescados"},{"name":"Brócoli","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Zanahoria","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Mantequilla","qty":15,"unit":"g","category":"Aceites y condimentos"}]', false),
('lunch_2', 'Merluza al horno con limón', 'Merluza fresca al horno con limón, aceite de oliva y hierbas aromáticas', 380, 52, 8, 16, '["omega-3"]', 'none', NULL, '[{"name":"Merluza fresca","qty":300,"unit":"g","category":"Pescados"},{"name":"Limón","qty":1,"unit":"unidad","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"},{"name":"Perejil","qty":10,"unit":"g","category":"Verduras y frutas"}]', false),
('lunch_3', 'Lubina a la sal con ensalada verde', 'Lubina fresca cocinada a la sal con ensalada mixta', 440, 55, 6, 22, '["omega-3","anti-inflam"]', 'none', NULL, '[{"name":"Lubina fresca","qty":350,"unit":"g","category":"Pescados"},{"name":"Lechuga","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Tomate","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_4', 'Trucha con almendras y espinacas', 'Trucha asada con almendras tostadas y espinacas salteadas', 480, 50, 10, 26, '["lunch","dinner","omega-3","gut"]', 'none', NULL, '[{"name":"Trucha fresca","qty":280,"unit":"g","category":"Pescados"},{"name":"Espinacas frescas","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Almendras","qty":30,"unit":"g","category":"Frutos secos y semillas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_5', 'Dorada al papillote con vegetales', 'Dorada cocinada en papillote con zanahoria, calabacín y hierbas', 410, 48, 14, 18, '["omega-3"]', 'none', NULL, '[{"name":"Dorada fresca","qty":320,"unit":"g","category":"Pescados"},{"name":"Calabacín","qty":120,"unit":"g","category":"Verduras y frutas"},{"name":"Zanahoria","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_6', 'Atún a la plancha con quinua', 'Atún fresco a la plancha con quinua y verduras salteadas', 550, 52, 35, 20, '["omega-3","quick"]', 'none', NULL, '[{"name":"Atún fresco","qty":280,"unit":"g","category":"Pescados"},{"name":"Quinua cocida","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Pimiento rojo","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_7', 'Pollo con hierbas y batata', 'Pechuga de pollo asada con hierbas aromáticas y batata al horno', 480, 50, 32, 14, '["quick"]', 'none', NULL, '[{"name":"Pechuga de pollo","qty":250,"unit":"g","category":"Carnes"},{"name":"Batata","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Tomillo fresco","qty":5,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_8', 'Pavo asado con manzana y jengibre', 'Lomo de pavo asado con manzana, jengibre fresco y especias', 420, 55, 24, 12, '[]', 'none', NULL, '[{"name":"Pechuga de pavo","qty":280,"unit":"g","category":"Carnes"},{"name":"Manzana","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Jengibre fresco","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_9', 'Huevos revueltos con aguacate', 'Huevos ecológicos revueltos con aguacate fresco y tostadas integrales', 480, 28, 24, 30, '["snack","quick","gut"]', 'none', NULL, '[{"name":"Huevo grande","qty":3,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Aguacate","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Pan integral","qty":50,"unit":"g","category":"Cereales y legumbres"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_10', 'Lentejas rojas con verduras', 'Lentejas rojas cocidas con zanahoria, cebolla y espinacas', 380, 22, 48, 8, '["gut"]', 'none', NULL, '[{"name":"Lentejas rojas","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Zanahoria","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Espinacas","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_11', 'Arroz integral con champiñones', 'Arroz integral de grano largo con champiñones salteados y ajo', 420, 14, 58, 12, '["quick","gut"]', 'none', NULL, '[{"name":"Arroz integral","qty":200,"unit":"g","category":"Cereales y legumbres"},{"name":"Champiñones frescos","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_12', 'Garbanzos tostados con especias', 'Garbanzos cocidos y tostados con comino, paprika y sal marina', 390, 18, 50, 14, '["snack","quick"]', 'none', NULL, '[{"name":"Garbanzos cocidos","qty":200,"unit":"g","category":"Cereales y legumbres"},{"name":"Comino","qty":2,"unit":"g","category":"Aceites y condimentos"},{"name":"Paprika","qty":2,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false);

-- Insert dinner recipes (12)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('dinner_1', 'Bacalao a la vizcaína', 'Bacalao fresco en salsa de pimiento rojo y cebolla', 420, 50, 16, 16, '["omega-3","anti-inflam"]', 'none', NULL, '[{"name":"Bacalao fresco","qty":300,"unit":"g","category":"Pescados"},{"name":"Pimiento rojo","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_2', 'Rape a la gallega', 'Rape fresco con patata cocida y aceite de ajo', 380, 55, 20, 10, '["omega-3","quick"]', 'none', NULL, '[{"name":"Rape fresco","qty":350,"unit":"g","category":"Pescados"},{"name":"Patata cocida","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_3', 'Sardinas a la plancha con tomate', 'Sardinas frescas a la plancha con ensalada de tomate y cebolla', 450, 52, 8, 24, '["omega-3","anti-inflam","quick"]', 'none', NULL, '[{"name":"Sardinas frescas","qty":300,"unit":"g","category":"Pescados"},{"name":"Tomate","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":60,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_4', 'Camarones al ajillo', 'Camarones frescos salteados con ajo, perejil y aceite de oliva', 280, 40, 6, 12, '["omega-3","quick"]', 'none', NULL, '[{"name":"Camarones frescos","qty":280,"unit":"g","category":"Pescados"},{"name":"Ajo","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Perejil","qty":15,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_5', 'Sepia a la tinta con arroz', 'Sepia fresca en su tinta con arroz negro y alioli casero', 520, 48, 45, 18, '["dinner","omega-3","gut"]', 'none', NULL, '[{"name":"Sepia fresca","qty":280,"unit":"g","category":"Pescados"},{"name":"Arroz negro","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Huevo","qty":1,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Ajo","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_6', 'Pez espada con champiñones', 'Pez espada asado con champiñones, ajo y vino blanco', 460, 52, 12, 22, '["omega-3","anti-inflam"]', 'none', NULL, '[{"name":"Pez espada","qty":300,"unit":"g","category":"Pescados"},{"name":"Champiñones frescos","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Vino blanco","qty":100,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_7', 'Caldo de verduras con fideos integrales', 'Caldo casero de verduras con fideos integrales y hierbas frescas', 320, 14, 48, 8, '["gut","quick"]', 'none', NULL, '[{"name":"Fideos integrales","qty":100,"unit":"g","category":"Cereales y legumbres"},{"name":"Caldo de verduras","qty":500,"unit":"ml","category":"Verduras y frutas"},{"name":"Zanahoria","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Apio","qty":60,"unit":"g","category":"Verduras y frutas"},{"name":"Perejil","qty":15,"unit":"g","category":"Verduras y frutas"}]', false),
('dinner_8', 'Crema de calabaza y jengibre', 'Crema ligera de calabaza con jengibre fresco y caldo de verduras', 280, 8, 38, 10, '["anti-inflam","gut","quick"]', 'none', NULL, '[{"name":"Calabaza","qty":400,"unit":"g","category":"Verduras y frutas"},{"name":"Jengibre fresco","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Caldo de verduras","qty":400,"unit":"ml","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_9', 'Brócoli gratinado con queso de cabra', 'Brócoli al vapor con queso de cabra fundido y nueces', 380, 20, 24, 24, '["gut"]', 'none', NULL, '[{"name":"Brócoli","qty":300,"unit":"g","category":"Verduras y frutas"},{"name":"Queso de cabra","qty":80,"unit":"g","category":"Lacteos y huevos"},{"name":"Nueces","qty":40,"unit":"g","category":"Frutos secos y semillas"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_10', 'Sopa minestrone con verduras', 'Sopa tradicional italiana con verduras frescas y frijoles cannellini', 340, 16, 50, 8, '["gut","quick"]', 'none', NULL, '[{"name":"Tomate enlatado","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Frijoles cannellini","qty":100,"unit":"g","category":"Cereales y legumbres"},{"name":"Cebolla","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Zanahoria","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Apio","qty":60,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_11', 'Espinacas salteadas con ajo', 'Espinacas frescas salteadas con ajo y aceite de oliva virgen', 180, 8, 8, 12, '["anti-inflam","quick"]', 'none', NULL, '[{"name":"Espinacas frescas","qty":400,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":12,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_12', 'Alcachofas al limón', 'Alcachofas frescas cocidas con limón fresco y aceite de oliva', 220, 10, 18, 12, '["anti-inflam","gut","quick"]', 'none', NULL, '[{"name":"Alcachofas frescas","qty":400,"unit":"g","category":"Verduras y frutas"},{"name":"Limón","qty":1,"unit":"unidad","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false);

-- Insert snack recipes (10)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('snack_1', 'Manzana con almendras', 'Manzana fresca con almendras crudas tostadas', 240, 8, 28, 12, '["snack","quick","anti-inflam"]', 'none', NULL, '[{"name":"Manzana roja","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Almendras crudas","qty":30,"unit":"g","category":"Frutos secos y semillas"}]', false),
('snack_2', 'Aguacate con limón y sal', 'Medio aguacate fresco con limón y sal marina', 200, 3, 10, 18, '["snack","quick","anti-inflam"]', 'none', NULL, '[{"name":"Aguacate","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Limón","qty":0.5,"unit":"unidad","category":"Verduras y frutas"},{"name":"Sal marina","qty":2,"unit":"g","category":"Aceites y condimentos"}]', false),
('snack_3', 'Yogur natural con fresas', 'Yogur natural sin azúcar con fresas frescas', 150, 12, 18, 3, '["snack","quick","gut"]', 'none', NULL, '[{"name":"Yogur natural desnatado","qty":150,"unit":"g","category":"Lacteos y huevos"},{"name":"Fresas frescas","qty":120,"unit":"g","category":"Verduras y frutas"}]', false),
('snack_4', 'Nueces y pasas', 'Puñado de nueces crudas con pasas de uva', 260, 8, 28, 16, '["snack","quick","anti-inflam"]', 'none', NULL, '[{"name":"Nueces crudas","qty":40,"unit":"g","category":"Frutos secos y semillas"},{"name":"Pasas de uva","qty":30,"unit":"g","category":"Verduras y frutas"}]', false),
('snack_5', 'Salmón ahumado con pepino', 'Salmón ahumado de calidad con rodajas de pepino fresco', 220, 24, 4, 12, '["snack","omega-3","quick"]', 'none', NULL, '[{"name":"Salmón ahumado","qty":60,"unit":"g","category":"Pescados"},{"name":"Pepino fresco","qty":200,"unit":"g","category":"Verduras y frutas"}]', false),
('snack_6', 'Queso fresco con tomate', 'Queso fresco desnatado con tomate cherry y orégano', 180, 18, 8, 8, '["snack","quick"]', 'none', NULL, '[{"name":"Queso fresco","qty":80,"unit":"g","category":"Lacteos y huevos"},{"name":"Tomate cherry","qty":120,"unit":"g","category":"Verduras y frutas"},{"name":"Orégano","qty":2,"unit":"g","category":"Aceites y condimentos"}]', false),
('snack_7', 'Smoothie de frutos rojos', 'Batido casero de frutos rojos con leche de almendra', 220, 8, 32, 6, '["snack","quick","anti-inflam"]', 'none', NULL, '[{"name":"Frutos rojos congelados","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Leche de almendra","qty":200,"unit":"ml","category":"Lacteos y huevos"},{"name":"Miel","qty":10,"unit":"g","category":"Aceites y condimentos"}]', false),
('snack_8', 'Hummus casero con zanahorias', 'Hummus de garbanzos casero con zanahorias crudas', 240, 10, 28, 10, '["snack","quick","gut"]', 'none', NULL, '[{"name":"Garbanzos cocidos","qty":100,"unit":"g","category":"Cereales y legumbres"},{"name":"Tahini","qty":15,"unit":"g","category":"Frutos secos y semillas"},{"name":"Limón","qty":0.5,"unit":"unidad","category":"Verduras y frutas"},{"name":"Zanahoria cruda","qty":150,"unit":"g","category":"Verduras y frutas"}]', false),
('snack_9', 'Kéfir con granola sin azúcar', 'Kéfir probiótico con granola casera sin azúcar añadido', 280, 16, 32, 10, '["snack","gut","quick"]', 'none', NULL, '[{"name":"Kéfir natural","qty":180,"unit":"g","category":"Lacteos y huevos"},{"name":"Granola sin azúcar","qty":40,"unit":"g","category":"Cereales y legumbres"}]', false),
('snack_10', 'Té verde con almendra tostada', 'Taza de té verde con un puñado de almendras tostadas', 180, 7, 14, 11, '["snack","quick","anti-inflam"]', 'none', NULL, '[{"name":"Té verde","qty":250,"unit":"ml","category":"Aceites y condimentos"},{"name":"Almendras tostadas","qty":30,"unit":"g","category":"Frutos secos y semillas"}]', false);

-- Insert 4 new caution recipes
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('caution_1', 'Entrecot a la plancha con ensalada', 'Entrecot premium a la plancha con ensalada mixta de temporada', 680, 68, 8, 38, '[]', 'caution', 'Carne roja: máx 1-2x/semana. Ácido araquidónico pro-inflamatorio.', '[{"name":"Entrecot de vaca","qty":350,"unit":"g","category":"Carnes"},{"name":"Lechuga mixta","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Tomate","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Zanahoria rallada","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":15,"unit":"ml","category":"Aceites y condimentos"}]', false),
('caution_2', 'Hamburguesa casera de ternera sin pan', 'Hamburguesa de ternera picada con cebolla y especias, sin pan', 520, 62, 6, 28, '[]', 'caution', 'Carne roja: máx 1-2x/semana. Ácido araquidónico pro-inflamatorio.', '[{"name":"Ternera picada magra","qty":300,"unit":"g","category":"Carnes"},{"name":"Cebolla","qty":60,"unit":"g","category":"Verduras y frutas"},{"name":"Perejil fresco","qty":15,"unit":"g","category":"Verduras y frutas"},{"name":"Huevo","qty":1,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('caution_3', 'Pasta boloñesa integral', 'Pasta integral con salsa boloñesa casera de carne magra', 580, 42, 62, 16, '[]', 'caution', 'Carne roja: máx 1-2x/semana. Carbohidratos refinados moderados.', '[{"name":"Pasta integral","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Carne de res picada","qty":250,"unit":"g","category":"Carnes"},{"name":"Tomate enlatado","qty":300,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('caution_4', 'Costillas de cerdo al horno', 'Costillas de cerdo al horno con especias y salsa de tomate', 640, 58, 12, 38, '[]', 'caution', 'Carne grasa: máx 1x/semana. Alto contenido en ácidos grasos saturados.', '[{"name":"Costillas de cerdo","qty":400,"unit":"g","category":"Carnes"},{"name":"Tomate triturado","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Pimentón","qty":5,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false);

-- Create indexes for better query performance
CREATE INDEX idx_recipes_tags ON recipes(tags);
CREATE INDEX idx_recipes_warning_level ON recipes(warning_level);
CREATE INDEX idx_meal_plans_created_at ON meal_plans(created_at);
