-- ============================================================
-- RECIPES V2: Update existing tags + 30 new recipes
-- Run AFTER the original recipes.sql seed
-- ============================================================

-- ============================================================
-- PART 1: Update existing recipes to have richer tags
-- ============================================================

-- Lunch recipes: add meal type + nutritional tags
UPDATE recipes SET tags = '["lunch","omega-3","anti-inflam","high-protein"]' WHERE id = 'lunch_1';
UPDATE recipes SET tags = '["lunch","omega-3","high-protein","low-carb"]' WHERE id = 'lunch_2';
UPDATE recipes SET tags = '["lunch","omega-3","anti-inflam","high-protein","low-carb"]' WHERE id = 'lunch_3';
UPDATE recipes SET tags = '["lunch","omega-3","gut","high-protein"]' WHERE id = 'lunch_4';
UPDATE recipes SET tags = '["lunch","omega-3","high-protein"]' WHERE id = 'lunch_5';
UPDATE recipes SET tags = '["lunch","omega-3","quick","high-protein"]' WHERE id = 'lunch_6';
UPDATE recipes SET tags = '["lunch","quick","high-protein"]' WHERE id = 'lunch_7';
UPDATE recipes SET tags = '["lunch","high-protein","low-carb"]' WHERE id = 'lunch_8';
UPDATE recipes SET tags = '["breakfast","snack","quick","gut"]' WHERE id = 'lunch_9';
UPDATE recipes SET tags = '["lunch","gut","batch-cook","anti-inflam"]' WHERE id = 'lunch_10';
UPDATE recipes SET tags = '["lunch","quick","gut","batch-cook"]' WHERE id = 'lunch_11';
UPDATE recipes SET tags = '["snack","quick","batch-cook"]' WHERE id = 'lunch_12';

-- Dinner recipes: add meal type + nutritional tags
UPDATE recipes SET tags = '["dinner","omega-3","anti-inflam","high-protein"]' WHERE id = 'dinner_1';
UPDATE recipes SET tags = '["dinner","omega-3","quick","high-protein"]' WHERE id = 'dinner_2';
UPDATE recipes SET tags = '["dinner","omega-3","anti-inflam","quick","high-protein"]' WHERE id = 'dinner_3';
UPDATE recipes SET tags = '["dinner","omega-3","quick","high-protein","low-carb"]' WHERE id = 'dinner_4';
UPDATE recipes SET tags = '["dinner","omega-3","gut","high-protein"]' WHERE id = 'dinner_5';
UPDATE recipes SET tags = '["dinner","omega-3","anti-inflam","high-protein","low-carb"]' WHERE id = 'dinner_6';
UPDATE recipes SET tags = '["dinner","gut","quick","low-carb"]' WHERE id = 'dinner_7';
UPDATE recipes SET tags = '["dinner","anti-inflam","gut","quick","low-carb","batch-cook"]' WHERE id = 'dinner_8';
UPDATE recipes SET tags = '["dinner","gut","low-carb"]' WHERE id = 'dinner_9';
UPDATE recipes SET tags = '["dinner","gut","quick","batch-cook"]' WHERE id = 'dinner_10';
UPDATE recipes SET tags = '["dinner","anti-inflam","quick","low-carb"]' WHERE id = 'dinner_11';
UPDATE recipes SET tags = '["dinner","anti-inflam","gut","quick","low-carb"]' WHERE id = 'dinner_12';

-- Snack recipes: already tagged, add nutritional tags
UPDATE recipes SET tags = '["snack","quick","anti-inflam","low-carb"]' WHERE id = 'snack_1';
UPDATE recipes SET tags = '["snack","quick","anti-inflam","low-carb"]' WHERE id = 'snack_2';
UPDATE recipes SET tags = '["snack","quick","gut","low-carb"]' WHERE id = 'snack_3';
UPDATE recipes SET tags = '["snack","quick","anti-inflam"]' WHERE id = 'snack_4';
UPDATE recipes SET tags = '["snack","omega-3","quick","high-protein","low-carb"]' WHERE id = 'snack_5';
UPDATE recipes SET tags = '["snack","quick","high-protein","low-carb"]' WHERE id = 'snack_6';
UPDATE recipes SET tags = '["snack","quick","anti-inflam","gut"]' WHERE id = 'snack_7';
UPDATE recipes SET tags = '["snack","quick","gut","batch-cook"]' WHERE id = 'snack_8';
UPDATE recipes SET tags = '["snack","gut","quick"]' WHERE id = 'snack_9';
UPDATE recipes SET tags = '["snack","quick","anti-inflam","low-carb"]' WHERE id = 'snack_10';

-- Caution recipes: add meal type
UPDATE recipes SET tags = '["dinner","high-protein","low-carb"]' WHERE id = 'caution_1';
UPDATE recipes SET tags = '["lunch","high-protein","low-carb","quick"]' WHERE id = 'caution_2';
UPDATE recipes SET tags = '["lunch","dinner"]' WHERE id = 'caution_3';
UPDATE recipes SET tags = '["dinner","high-protein"]' WHERE id = 'caution_4';


-- ============================================================
-- PART 2: 30 new recipes
-- ============================================================

-- BREAKFAST RECIPES (8)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('breakfast_1', 'Bowl de avena con arandanos y nueces', 'Avena cocida con arandanos frescos, nueces y un toque de canela', 380, 14, 48, 16, '["breakfast","gut","anti-inflam","batch-cook"]', 'none', NULL, '[{"name":"Avena en copos","qty":80,"unit":"g","category":"Cereales y legumbres"},{"name":"Arandanos frescos","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Nueces","qty":25,"unit":"g","category":"Frutos secos y semillas"},{"name":"Canela","qty":3,"unit":"g","category":"Aceites y condimentos"},{"name":"Leche de almendra","qty":200,"unit":"ml","category":"Lacteos y huevos"}]', false),
('breakfast_2', 'Tortilla de espinacas y queso de cabra', 'Tortilla jugosa de espinacas con queso de cabra desmenuzado', 340, 26, 4, 24, '["breakfast","quick","high-protein","low-carb"]', 'none', NULL, '[{"name":"Huevo grande","qty":3,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Espinacas frescas","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Queso de cabra","qty":40,"unit":"g","category":"Lacteos y huevos"},{"name":"Aceite de oliva","qty":8,"unit":"ml","category":"Aceites y condimentos"}]', false),
('breakfast_3', 'Tostadas de salmon ahumado y aguacate', 'Pan de centeno con salmon ahumado, aguacate y semillas de sesamo', 420, 28, 30, 22, '["breakfast","omega-3","high-protein"]', 'none', NULL, '[{"name":"Pan de centeno","qty":80,"unit":"g","category":"Cereales y legumbres"},{"name":"Salmon ahumado","qty":80,"unit":"g","category":"Pescados"},{"name":"Aguacate","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Semillas de sesamo","qty":10,"unit":"g","category":"Frutos secos y semillas"}]', false),
('breakfast_4', 'Smoothie bowl de platano y espirulina', 'Bowl cremoso de platano congelado con espirulina, granola y semillas de chia', 350, 12, 52, 12, '["breakfast","gut","anti-inflam","quick"]', 'none', NULL, '[{"name":"Platano congelado","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Espirulina","qty":5,"unit":"g","category":"Suplementos"},{"name":"Granola sin azucar","qty":30,"unit":"g","category":"Cereales y legumbres"},{"name":"Semillas de chia","qty":15,"unit":"g","category":"Frutos secos y semillas"},{"name":"Leche de almendra","qty":100,"unit":"ml","category":"Lacteos y huevos"}]', false),
('breakfast_5', 'Huevos al horno con tomate y hierbas', 'Huevos horneados en salsa de tomate con oregano y albahaca', 290, 20, 12, 18, '["breakfast","quick","high-protein","low-carb","anti-inflam"]', 'none', NULL, '[{"name":"Huevo grande","qty":3,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Tomate triturado","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Oregano","qty":3,"unit":"g","category":"Aceites y condimentos"},{"name":"Albahaca fresca","qty":10,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('breakfast_6', 'Pudding de chia con mango', 'Pudding nocturno de semillas de chia con leche de coco y mango fresco', 310, 10, 36, 16, '["breakfast","gut","anti-inflam","batch-cook"]', 'none', NULL, '[{"name":"Semillas de chia","qty":40,"unit":"g","category":"Frutos secos y semillas"},{"name":"Leche de coco","qty":200,"unit":"ml","category":"Lacteos y huevos"},{"name":"Mango fresco","qty":120,"unit":"g","category":"Verduras y frutas"},{"name":"Miel","qty":10,"unit":"g","category":"Aceites y condimentos"}]', false),
('breakfast_7', 'Crepes de avena con frutos rojos', 'Crepes saludables de avena y huevo con frutos rojos frescos', 360, 18, 44, 12, '["breakfast","gut","quick"]', 'none', NULL, '[{"name":"Avena en copos","qty":60,"unit":"g","category":"Cereales y legumbres"},{"name":"Huevo grande","qty":2,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Frutos rojos","qty":120,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de coco","qty":5,"unit":"ml","category":"Aceites y condimentos"}]', false),
('breakfast_8', 'Yogur griego con semillas y miel', 'Yogur griego natural con mix de semillas, miel cruda y canela', 280, 20, 24, 12, '["breakfast","snack","quick","gut","high-protein"]', 'none', NULL, '[{"name":"Yogur griego natural","qty":200,"unit":"g","category":"Lacteos y huevos"},{"name":"Semillas de calabaza","qty":15,"unit":"g","category":"Frutos secos y semillas"},{"name":"Semillas de lino","qty":10,"unit":"g","category":"Frutos secos y semillas"},{"name":"Miel cruda","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Canela","qty":2,"unit":"g","category":"Aceites y condimentos"}]', false);

-- LUNCH RECIPES (8)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('lunch_13', 'Ensalada de caballa con aguacate y quinua', 'Caballa a la plancha sobre base de quinua con aguacate y vinagreta de limon', 520, 38, 32, 26, '["lunch","omega-3","anti-inflam","high-protein"]', 'none', NULL, '[{"name":"Caballa fresca","qty":200,"unit":"g","category":"Pescados"},{"name":"Quinua cocida","qty":120,"unit":"g","category":"Cereales y legumbres"},{"name":"Aguacate","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Limon","qty":1,"unit":"unidad","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_14', 'Curry de garbanzos con espinacas', 'Curry suave de garbanzos con espinacas, leche de coco y curcuma', 420, 18, 46, 18, '["lunch","gut","anti-inflam","batch-cook"]', 'none', NULL, '[{"name":"Garbanzos cocidos","qty":200,"unit":"g","category":"Cereales y legumbres"},{"name":"Espinacas frescas","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Leche de coco","qty":150,"unit":"ml","category":"Lacteos y huevos"},{"name":"Curcuma","qty":5,"unit":"g","category":"Aceites y condimentos"},{"name":"Jengibre fresco","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_15', 'Poke bowl de salmon y edamame', 'Bowl hawaiano con salmon fresco, arroz integral, edamame y salsa de soja', 540, 42, 48, 18, '["lunch","omega-3","high-protein","gut"]', 'none', NULL, '[{"name":"Salmon fresco","qty":180,"unit":"g","category":"Pescados"},{"name":"Arroz integral cocido","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Edamame","qty":80,"unit":"g","category":"Cereales y legumbres"},{"name":"Pepino","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Salsa de soja","qty":15,"unit":"ml","category":"Aceites y condimentos"},{"name":"Semillas de sesamo","qty":10,"unit":"g","category":"Frutos secos y semillas"}]', false),
('lunch_16', 'Wok de pollo con verduras y jengibre', 'Salteado rapido de pollo con brocoli, pimiento y jengibre fresco', 440, 48, 18, 20, '["lunch","quick","high-protein","low-carb","anti-inflam"]', 'none', NULL, '[{"name":"Pechuga de pollo","qty":250,"unit":"g","category":"Carnes"},{"name":"Brocoli","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Pimiento rojo","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Jengibre fresco","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de sesamo","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_17', 'Ensalada mediterranea de atun', 'Atun en conserva al natural con tomate, pepino, aceitunas y aceite de oliva', 380, 36, 12, 22, '["lunch","omega-3","quick","high-protein","low-carb"]', 'none', NULL, '[{"name":"Atun en conserva al natural","qty":200,"unit":"g","category":"Pescados"},{"name":"Tomate","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Pepino","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceitunas negras","qty":30,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":15,"unit":"ml","category":"Aceites y condimentos"}]', false),
('lunch_18', 'Buddha bowl de boniato y garbanzos', 'Bowl completo con boniato asado, garbanzos especiados, kale y tahini', 480, 18, 56, 22, '["lunch","gut","anti-inflam","batch-cook"]', 'none', NULL, '[{"name":"Boniato","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Garbanzos cocidos","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Kale","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Tahini","qty":20,"unit":"g","category":"Frutos secos y semillas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"},{"name":"Comino","qty":3,"unit":"g","category":"Aceites y condimentos"}]', false),
('lunch_19', 'Sopa de miso con tofu y algas', 'Sopa japonesa reconfortante con tofu sedoso, algas wakame y cebolleta', 220, 16, 18, 8, '["lunch","dinner","gut","anti-inflam","low-carb","quick"]', 'none', NULL, '[{"name":"Pasta de miso","qty":30,"unit":"g","category":"Aceites y condimentos"},{"name":"Tofu sedoso","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Algas wakame","qty":5,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolleta","qty":30,"unit":"g","category":"Verduras y frutas"}]', false),
('lunch_20', 'Revuelto de setas silvestres con ajo', 'Variedad de setas salteadas con ajo, perejil y huevos ecologicos', 320, 22, 8, 22, '["lunch","quick","high-protein","low-carb","gut"]', 'none', NULL, '[{"name":"Setas variadas","qty":250,"unit":"g","category":"Verduras y frutas"},{"name":"Huevo grande","qty":3,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Ajo","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Perejil fresco","qty":15,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false);

-- DINNER RECIPES (8)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('dinner_13', 'Salmon al horno con costra de frutos secos', 'Salmon con costra de almendras y pistachos, acompanado de esparragos', 560, 48, 8, 36, '["dinner","omega-3","anti-inflam","high-protein","low-carb"]', 'none', NULL, '[{"name":"Salmon fresco","qty":250,"unit":"g","category":"Pescados"},{"name":"Almendras molidas","qty":25,"unit":"g","category":"Frutos secos y semillas"},{"name":"Pistachos","qty":15,"unit":"g","category":"Frutos secos y semillas"},{"name":"Esparragos","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_14', 'Crema de brocoli con almendras', 'Crema sedosa de brocoli con almendras tostadas y aceite de oliva virgen', 280, 12, 20, 18, '["dinner","anti-inflam","gut","low-carb","batch-cook"]', 'none', NULL, '[{"name":"Brocoli","qty":400,"unit":"g","category":"Verduras y frutas"},{"name":"Almendras","qty":30,"unit":"g","category":"Frutos secos y semillas"},{"name":"Cebolla","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Caldo de verduras","qty":300,"unit":"ml","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_15', 'Caballa al horno con pisto manchego', 'Caballa fresca al horno sobre base de pisto de verduras mediterraneas', 440, 40, 16, 24, '["dinner","omega-3","anti-inflam","high-protein","batch-cook"]', 'none', NULL, '[{"name":"Caballa fresca","qty":280,"unit":"g","category":"Pescados"},{"name":"Calabacin","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Berenjena","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Pimiento rojo","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Tomate","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_16', 'Ensalada templada de lentejas y salmon', 'Lentejas verdes con salmon a la plancha, rucula y vinagreta de mostaza', 480, 42, 32, 20, '["dinner","omega-3","gut","high-protein","anti-inflam"]', 'none', NULL, '[{"name":"Salmon fresco","qty":180,"unit":"g","category":"Pescados"},{"name":"Lentejas verdes cocidas","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Rucula","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Mostaza de Dijon","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":12,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_17', 'Pollo al limon con curcuma y arroz basmati', 'Muslos de pollo marinados en limon y curcuma con arroz basmati', 510, 46, 40, 16, '["dinner","anti-inflam","high-protein","batch-cook"]', 'none', NULL, '[{"name":"Muslos de pollo","qty":280,"unit":"g","category":"Carnes"},{"name":"Arroz basmati","qty":120,"unit":"g","category":"Cereales y legumbres"},{"name":"Curcuma","qty":5,"unit":"g","category":"Aceites y condimentos"},{"name":"Limon","qty":1,"unit":"unidad","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_18', 'Gazpacho andaluz con gambas', 'Gazpacho frio tradicional con gambas a la plancha y aceite de oliva', 300, 28, 22, 12, '["dinner","omega-3","anti-inflam","quick","low-carb"]', 'none', NULL, '[{"name":"Tomate maduro","qty":400,"unit":"g","category":"Verduras y frutas"},{"name":"Gambas frescas","qty":150,"unit":"g","category":"Pescados"},{"name":"Pepino","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Pimiento verde","qty":60,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":15,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_19', 'Tortilla de calabacin y cebolla caramelizada', 'Tortilla jugosa de calabacin con cebolla lentamente caramelizada', 340, 20, 14, 24, '["dinner","quick","low-carb","gut"]', 'none', NULL, '[{"name":"Huevo grande","qty":4,"unit":"unidad","category":"Lacteos y huevos"},{"name":"Calabacin","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":150,"unit":"g","category":"Verduras y frutas"},{"name":"Aceite de oliva","qty":15,"unit":"ml","category":"Aceites y condimentos"}]', false),
('dinner_20', 'Merluza en salsa verde con almejas', 'Merluza fresca en salsa verde de perejil con almejas y guisantes', 380, 52, 12, 14, '["dinner","omega-3","high-protein","low-carb"]', 'none', NULL, '[{"name":"Merluza fresca","qty":280,"unit":"g","category":"Pescados"},{"name":"Almejas","qty":150,"unit":"g","category":"Pescados"},{"name":"Guisantes","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Perejil fresco","qty":20,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":10,"unit":"ml","category":"Aceites y condimentos"}]', false);

-- SNACK & BATCH-COOK RECIPES (6)
INSERT INTO recipes (id, name, description, kcal, protein, carbs, fat, tags, warning_level, warning_reason, ingredients, is_custom) VALUES
('snack_11', 'Energy balls de datiles y cacao', 'Bolitas energeticas de datiles, almendras, cacao puro y coco rallado', 220, 6, 30, 10, '["snack","quick","anti-inflam","batch-cook"]', 'none', NULL, '[{"name":"Datiles Medjool","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Almendras","qty":30,"unit":"g","category":"Frutos secos y semillas"},{"name":"Cacao puro en polvo","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Coco rallado","qty":15,"unit":"g","category":"Frutos secos y semillas"}]', false),
('snack_12', 'Edamame con sal marina y limon', 'Vainas de edamame al vapor con sal marina gruesa y zumo de limon', 180, 16, 12, 8, '["snack","quick","high-protein","low-carb","gut"]', 'none', NULL, '[{"name":"Edamame en vaina","qty":200,"unit":"g","category":"Cereales y legumbres"},{"name":"Sal marina","qty":3,"unit":"g","category":"Aceites y condimentos"},{"name":"Limon","qty":0.5,"unit":"unidad","category":"Verduras y frutas"}]', false),
('snack_13', 'Batido verde anti-inflamatorio', 'Batido de espinacas, pepino, jengibre, manzana verde y limon', 160, 4, 32, 2, '["snack","breakfast","quick","anti-inflam","gut","low-carb"]', 'none', NULL, '[{"name":"Espinacas frescas","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Pepino","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Jengibre fresco","qty":10,"unit":"g","category":"Aceites y condimentos"},{"name":"Manzana verde","qty":120,"unit":"g","category":"Verduras y frutas"},{"name":"Limon","qty":0.5,"unit":"unidad","category":"Verduras y frutas"}]', false),
('batch_1', 'Chili de pavo y alubias negras', 'Chili reconfortante de pavo picado con alubias negras, tomate y especias', 420, 42, 34, 12, '["lunch","dinner","high-protein","gut","batch-cook"]', 'none', NULL, '[{"name":"Pavo picado","qty":250,"unit":"g","category":"Carnes"},{"name":"Alubias negras cocidas","qty":150,"unit":"g","category":"Cereales y legumbres"},{"name":"Tomate triturado","qty":200,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Comino","qty":3,"unit":"g","category":"Aceites y condimentos"},{"name":"Pimenton ahumado","qty":3,"unit":"g","category":"Aceites y condimentos"}]', false),
('batch_2', 'Caldo de huesos con verduras', 'Caldo nutritivo de huesos de pollo con verduras, curcuma y jengibre', 120, 10, 6, 6, '["dinner","gut","anti-inflam","low-carb","batch-cook"]', 'none', NULL, '[{"name":"Huesos de pollo","qty":500,"unit":"g","category":"Carnes"},{"name":"Zanahoria","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Apio","qty":80,"unit":"g","category":"Verduras y frutas"},{"name":"Cebolla","qty":100,"unit":"g","category":"Verduras y frutas"},{"name":"Curcuma","qty":5,"unit":"g","category":"Aceites y condimentos"},{"name":"Jengibre fresco","qty":10,"unit":"g","category":"Aceites y condimentos"}]', false),
('batch_3', 'Salsa de tomate casera anti-inflamatoria', 'Salsa de tomate con ajo, albahaca, curcuma y aceite de oliva virgen extra', 140, 4, 16, 8, '["lunch","dinner","anti-inflam","gut","batch-cook"]', 'none', NULL, '[{"name":"Tomate maduro","qty":500,"unit":"g","category":"Verduras y frutas"},{"name":"Ajo","qty":15,"unit":"g","category":"Aceites y condimentos"},{"name":"Albahaca fresca","qty":20,"unit":"g","category":"Verduras y frutas"},{"name":"Curcuma","qty":3,"unit":"g","category":"Aceites y condimentos"},{"name":"Aceite de oliva","qty":15,"unit":"ml","category":"Aceites y condimentos"}]', false);
